# Generated by Django 4.1.7 on 2023-03-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.IntegerField(verbose_name='Идентификатор')),
                ('VotingName', models.CharField(max_length=256, verbose_name='Название голосования')),
                ('LinkToResults', models.URLField(verbose_name='Ссылка на результаты')),
                ('VotingName_en', models.CharField(max_length=256, verbose_name='Англоязычное название')),
                ('LinkToResults_en', models.URLField(verbose_name='Англоязычные результаты')),
            ],
        ),
    ]
