# Generated by Django 4.1.7 on 2023-03-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.CharField(max_length=20, verbose_name='Идентификатор')),
                ('votingname', models.CharField(max_length=256, verbose_name='Название голосования')),
                ('linktoresults', models.URLField(verbose_name='Ссылка на результаты')),
                ('votingname_en', models.CharField(max_length=256, null=True, verbose_name='Англоязычное название')),
                ('linktoresults_en', models.URLField(null=True, verbose_name='Англоязычные результаты')),
            ],
            options={
                'verbose_name_plural': 'Голоса',
            },
        ),
    ]
