# Generated by Django 4.1.7 on 2023-03-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='LinkToResults',
            new_name='linktoresults',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='LinkToResults_en',
            new_name='linktoresults_en',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='VotingName',
            new_name='votingname',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='VotingName_en',
            new_name='votingname_en',
        ),
    ]
