# Generated by Django 4.1.7 on 2023-03-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_rename_linktoresults_votes_linktoresults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='global_id',
            field=models.CharField(max_length=20, verbose_name='Идентификатор'),
        ),
    ]
