# Generated by Django 4.1.7 on 2023-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_votes_global_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='linktoresults_en',
            field=models.URLField(null=True, verbose_name='Англоязычные результаты'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='votingname_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Англоязычное название'),
        ),
    ]
